### ISSUE TITLE
Release latest version to npm (type definitions are currently missing the config option 'runOnCompile')

### ISSUE THREAD

**Issue by chapati23** [unipeer/hardhat-typechain#1]
hey, the currently released npm package v0.3.3 is missing the `runOnCompile: boolean` config option causing typescript errors:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/117495/98244402-ac734b00-1f6f-11eb-95df-5fba05644ea9.png">

<img width="1205" alt="Pasted_Image_05_11_20__14_01" src="https://user-images.githubusercontent.com/117495/98244359-9b2a3e80-1f6f-11eb-896b-83f98a01df8f.png">

**Comment by shalzz** [comment]
Hi,

This is the repo for a fork plugin with a different package name `@unipeer/hardhat-typechain`
You are looking at the npm page for `hardhat-typechain` package.
You can find the npm page for this plugin here: https://www.npmjs.com/package/@unipeer/hardhat-typechain

**Comment by chapati23** [comment]
i'm sorry, you're right. i didn't notice there were two same-same-but-different versions of this out there!

moved this issue over to the right repo: https://github.com/rhlsthrm/hardhat-typechain/issues/9
